services:
  gnb_test:
    build: .
    container_name: gnb_test
    ports:
      - "8081:80"
    environment:
      - DB_NAME=gnb_test
      - DB_USER=gnb_test
      - DB_PASS=gnb_test
    volumes:
      - .:/var/www/html
      - ./data:/var/www/html/data
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
