version: '3.8'

services:
  gnb_test:
    build: .
    container_name: gnb_test
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./data:/var/www/html/data
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
